# Generated by Django 4.2.4 on 2023-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_remove_board_image_remove_board_view_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
    ]
